server:
  port: 8080

spring:
  application:
    name: Gateway
  cloud:
    consul:
      port: 8500
      host: localhost
    gateway:
      routes:
        - id: category_router  # 指定路由唯一标识
          uri: http://localhost:8787 # OpenFeignCategoryApplication :8787/；指定路由服务的地址
          predicates:  # 断言
            - Path=/Category/** # 访问http://localhost:8080/Category/...，自动跳转http://localhost:8787/Category

        - id: product_router  # 指定路由唯一标识
          # uri: http://localhost:8788 # OpenFeignProductApplication :8788/；指定路由服务的地址
          uri: lb://OpenFeignProduct # lb代表转发后台服务使用负载均衡，OpenFeignProduct代表服务注册中心上的服务名
          predicates: # 断言
            - Path=/Product/** # 访问http://localhost:8080/Product/...，自动跳转http://localhost:8788/Product