server:
  port: 8761

spring:
  application:
    name: eureka-security-server
  security:
    user:
      name: chenzf
      password: 123456

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
