# 1. 基本配置

server:
  port: 8084

spring:
  application:
    name: zuul-proxy

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# 2.  配置路由规则
zuul:
  routes:
    user-service:
      path: /userService/**
    feign-service:
      path: /feignService/**
  prefix: /Zuul-Proxy

# 3. 开启查看路由的端点
management:
  endpoints:
    web:
      exposure:
        include: 'routes'